services:
  client:
    container_name: squiz_client
    build: ./client
    image: squiz_client
    ports: 
      - 3000:3000
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: bash -c "npm install && npm start"
  server:
    container_name: squiz_dev_api
    ports: 
      - 3030:3030
    environment: 
      - DB_NAME=squiz_db
      - DB_CONNECTION=mongodb://squiz:squiz_db_pass@db:27017
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  socketIO:
    container_name: squiz_dev_socketIO
    ports: 
      - 5000:5000
    environment: 
      - DB_NAME=squiz_db
      - DB_CONNECTION=mongodb://squiz:squiz_db_pass@db:27017
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  db:
    container_name: squiz_dev_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=squiz
      - MONGO_INITDB_DATABASE=squiz_db
      - MONGO_INITDB_ROOT_PASSWORD=squiz_db_pass
volumes:
  dbdata:
networks: 
  default:
    name: squiz_api
