version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./server/api
        target: /code

  db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=squiz
    volumes:
      - "./server/db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
